### ISSUE TITLE
startup AssertionError: assert(trimmedRemainingGloss)

### ISSUE THREAD

**Issue by dcsan** [mistval/kotoba#105]
seeing this at startup. is this cause I don't have some required data files loaded/ setup?

```
(node:42586) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(trimmedRemainingGloss)

    at parseGloss (/Users/dc/dev/rnd/kotoba/bot/node_modules/edict-index/build_index.js:18:3)
    at Array.map (<anonymous>)
    at createDocumentForEdictLine (/Users/dc/dev/rnd/kotoba/bot/node_modules/edict-index/build_index.js:88:45)
    at lines.forEach (/Users/dc/dev/rnd/kotoba/bot/node_modules/edict-index/build_index.js:129:25)
    at Array.forEach (<anonymous>)
    at Object.buildIndex (/Users/dc/dev/rnd/kotoba/bot/node_modules/edict-index/build_index.js:128:9)
    at getIndex (/Users/dc/dev/rnd/kotoba/bot/src/common/hispadic.js:42:28)
```

**Comment by dcsan** [comment]
I don't see anything here about grabbing edict data, so not sure...

https://github.com/mistval/kotoba#discord-bot

**Comment by mistval** [comment]
It's a bug in a dependency for the new Hispadic command. It's benign and can be safely ignored. I intend to fix it soon.
