### ISSUE TITLE
Exception in shiritori

### ISSUE THREAD

**Issue by mistval** [mistval/kotoba#45]
TypeError: Cannot read property '279811287729307649' of undefined
  Stack: TypeError: Cannot read property '279811287729307649' of undefined
    at createFieldForUsedWord (/home/xxx/commands/shiritori.js:50:43)
    at createFieldsForTookTurnEmbed (/home/xxx/commands/shiritori.js:62:17)
    at DiscordClientDelegate.playerTookTurn (/home/xxx/commands/shiritori.js:244:17)
    at tryShowCurrentState (/home/xxx/kotoba/shiritori/shiritori_manager.js:159:25)
    at promise.catch.then.then (/home/xxx/kotoba/shiritori/shiritori_manager.js:214:14)
    at <anonymous>

**Comment by mistval** [comment]
I've sort of lost track of this one, the code has changed enough that the line numbers in the trace are no longer helpful. I think there's a fair chance this is already fixed. Closing, but will reopen if it happens again.
