### ISSUE TITLE
Error when stopping Shiritori

### ISSUE THREAD

**Issue by mistval** [mistval/kotoba#55]
Seen once in error log, specific conditions unknown:

embed.fields.1.value: This field is required
Stack: DiscordRESTError [50035]: Invalid Form Body
embed.fields.1.value: This field is required

**Comment by mistval** [comment]
at DiscordClientDelegate.stopped (/home/xxx/commands/shiritori.js:153:42)
    at endGame (/home/xxx/kotoba/shiritori/shiritori_manager.js:88:42)
    at ShiritoriManager.stop (/home/xxx/kotoba/shiritori/shiritori_manager.js:466:12)
    at Command.action [as action_] (/home/xxx/commands/shiritori.js:309:31)
    at Command.invokeAction_ (/home/xxx/node_modules/monochrome-bot/core/command.js:218:17)
    at settingsGetter.getSettings.then.settings (/home/xxx/node_modules/monochrome-bot/core/command.js:189:21)

**Comment by mistval** [comment]
Fixed https://github.com/mistval/kotoba/commit/f056080f18fec0e69644ccc498c78823b3432551
